services:
  auth_db:
    image: postgres:15
    container_name: easylink_auth_db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - easylink_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build: ./auth-service
    container_name: easylink_auth_service
    ports:
      - "8000:8000"
    env_file:
      - ./auth-service/.env
    environment:
      - DATABASE_URL=postgresql://auth_user:auth_password@auth_db:5432/auth_db
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - easylink_network
    volumes:
      - ./auth-service:/app
    restart: unless-stopped

volumes:
  auth_db_data:

networks:
  easylink_network:
    driver: bridge
