services:
  auth_db:
    image: postgres:15
    container_name: easylink_auth_db
    env_file:
      - ./auth-service/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - easylink_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build: ./auth-service
    container_name: easylink_auth_service
    ports:
      - "8000:8000"
    env_file:
      - ./auth-service/.env
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - easylink_network
    volumes:
      - ./auth-service:/app
    restart: unless-stopped

volumes:
  auth_db_data:

networks:
  easylink_network:
    driver: bridge
